// Code generated by sqlc. DO NOT EDIT.

package repository

import (
	"context"
	"time"

	"github.com/google/uuid"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)

	CreateWallet(ctx context.Context, arg CreateWalletParams) (Wallet, error)
	DeleteWallet(ctx context.Context, arg DeleteWalletParams) error
	GetWalletByID(ctx context.Context, arg GetWalletByIDParams) (Wallet, error)
	GetWalletsByUserID(ctx context.Context, userID uuid.UUID) ([]Wallet, error)
	UpdateWallet(ctx context.Context, arg UpdateWalletParams) (Wallet, error)

	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	DeleteCategory(ctx context.Context, arg DeleteCategoryParams) error
	GetCategoryByID(ctx context.Context, arg GetCategoryByIDParams) (Category, error)
	GetCategoriesByUserID(ctx context.Context, userID uuid.UUID) ([]Category, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)

	CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error)
	GetTransactionByID(ctx context.Context, id uuid.UUID, userID uuid.UUID) (Transaction, error)
	UpdateTransaction(ctx context.Context, arg UpdateTransactionParams) (Transaction, error)
	DeleteTransaction(ctx context.Context, id uuid.UUID, userID uuid.UUID) error
	SearchTransactions(ctx context.Context, arg SearchTransactionsParams) ([]Transaction, int, error)

	GetDueRecurringTransactions(ctx context.Context, runDate time.Time) ([]RecurringTransaction, error)
	UpdateRecurringTransactionNextRun(ctx context.Context, id uuid.UUID, nextRunDate time.Time) error
}

var _ Querier = (*Queries)(nil)
