// Code generated by sqlc. DO NOT EDIT.

package repository

import (
	"context"

	"github.com/google/uuid"
)

const createWallet = `-- name: CreateWallet :one
INSERT INTO wallets (
  user_id, name, type, balance
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, user_id, name, type, balance, created_at
`

type CreateWalletParams struct {
	UserID  uuid.UUID `json:"user_id"`
	Name    string    `json:"name"`
	Type    string    `json:"type"`
	Balance float64   `json:"balance"`
}

func (q *Queries) CreateWallet(ctx context.Context, arg CreateWalletParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, createWallet,
		arg.UserID,
		arg.Name,
		arg.Type,
		arg.Balance,
	)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Balance,
		&i.CreatedAt,
	)
	return i, err
}

const deleteWallet = `-- name: DeleteWallet :exec
DELETE FROM wallets
WHERE id = $1 AND user_id = $2
`

type DeleteWalletParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) DeleteWallet(ctx context.Context, arg DeleteWalletParams) error {
	_, err := q.db.Exec(ctx, deleteWallet, arg.ID, arg.UserID)
	return err
}

const getWalletByID = `-- name: GetWalletByID :one
SELECT id, user_id, name, type, balance, created_at FROM wallets
WHERE id = $1 AND user_id = $2 LIMIT 1
`

type GetWalletByIDParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetWalletByID(ctx context.Context, arg GetWalletByIDParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, getWalletByID, arg.ID, arg.UserID)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Balance,
		&i.CreatedAt,
	)
	return i, err
}

const getWalletsByUserID = `-- name: GetWalletsByUserID :many
SELECT id, user_id, name, type, balance, created_at FROM wallets
WHERE user_id = $1
ORDER BY created_at DESC
`

func (q *Queries) GetWalletsByUserID(ctx context.Context, userID uuid.UUID) ([]Wallet, error) {
	rows, err := q.db.Query(ctx, getWalletsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Wallet
	for rows.Next() {
		var i Wallet
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Type,
			&i.Balance,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateWallet = `-- name: UpdateWallet :one
UPDATE wallets
SET name = $3, type = $4, balance = $5
WHERE id = $1 AND user_id = $2
RETURNING id, user_id, name, type, balance, created_at
`

type UpdateWalletParams struct {
	ID      uuid.UUID `json:"id"`
	UserID  uuid.UUID `json:"user_id"`
	Name    string    `json:"name"`
	Type    string    `json:"type"`
	Balance float64   `json:"balance"`
}

func (q *Queries) UpdateWallet(ctx context.Context, arg UpdateWalletParams) (Wallet, error) {
	row := q.db.QueryRow(ctx, updateWallet,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Type,
		arg.Balance,
	)
	var i Wallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Balance,
		&i.CreatedAt,
	)
	return i, err
}
